"
"	Jonathan Perkin <jonathan@perkin.org.uk> wrote this file.
"
" You can freely distribute/modify it (and are encouraged to do so),
" and you are welcome to buy me a beer if we ever meet and you think
" this stuff is worth it.  Improvements and cleanups always welcome.
"
" ~/.vimrc - main vim resource file.
"
"	https://www.vim.org/
"


"
" Miscellaneous settings.  "set nocompatible" must come first, as it affects
" the behaviour of subsequent settings.
"
set nocompatible	" disable vi compatibility
set nobackup		" don't keep backup files
set laststatus=2	" show status line
set nomodeline		" do not parse modes in files, big security risk
set ruler		" show the cursor position in status bar
set showmode		" show current mode in status bar
set spelllang=en_gb	" load native dictionary for spell check

"
" Enable hlsearch but only with specific settings.  Double-Esc turns off the
" matches, and there is a highlight override below to avoid the ugly defaults.
"
set hlsearch
set incsearch
nnoremap <silent> <Esc><Esc> <Esc>:nohlsearch<CR><Esc>

"
" Configure auto commands.
"
if has("autocmd")
	" Clear any existing auto commands
	autocmd!

	" Enable file type detection and customisation
	filetype plugin indent on

	" Filetype-based editing
	autocmd FileType python	set et sta sts=4 sw=4

	" Enable spell checker when editing mail
	autocmd FileType mail set spell
endif

"
" I cannot stand terminals which clear the screen after exiting.
"
set t_te=
set t_ti=

"
" Enable syntax highlighting if available.  My current terminal of choice is
" macOS Terminal.app with Solarized Light, and currently the best way to
" implement that is by forcing 16 colours.
"
if has("syntax") && (&t_Co > 2)
	syntax on
	set t_Co=16
	let g:solarized_statusline="flat"
	let g:solarized_italics=0
	colorscheme solarized8

	" Override ugly search highlight default
	highlight Search	ctermbg=7	cterm=none

	" Match	mutt colours
	highlight mailSubject	ctermfg=6	cterm=none
	highlight mailSignature	ctermfg=4	cterm=none
	highlight mailQuoted1	ctermfg=6	cterm=none
	highlight mailQuoted2	ctermfg=3	cterm=none
	highlight mailQuoted3	ctermfg=2	cterm=none
	highlight mailQuoted4	ctermfg=13	cterm=none
	highlight mailURL	ctermfg=13	cterm=none

	highlight! link	mailQuoted5 mailQuoted1
	highlight! link	mailQuoted6 mailQuoted2
	highlight! link	mailQuoted7 mailQuoted3
	highlight! link	mailQuoted8 mailQuoted4
endif
